name: Package Details
run-name: Package Details for ${{ github.event.registry_package.name }}

on:
  registry_package:
    types: [published]

jobs:
  show-package-details:
    runs-on: ubuntu-latest
    steps:
      - name: Display Package Information
        run: |
          echo "Package Details:"
          echo "----------------"
          echo "Package Name: ${{ github.event.registry_package.name }}"
          echo "Package Version: ${{ github.event.registry_package.package_version.version }}"
          echo "Registry: ${{ github.event.registry_package.registry }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Package URL: ${{ github.event.registry_package.html_url }}"
