name: Package Details
run-name: Package Details for ${{ github.event.registry_package.name }}

on:
  registry_package:
    types: [published]

jobs:
  show-package-details:
    runs-on: ubuntu-latest
    steps:
      - name: Display Package Information
        run: |
          echo "Package Details:"
          echo "----------------"
          echo "Package Name: ${{ github.event.registry_package.name }}"
          echo "Package Version: ${{ github.event.registry_package.package_version.version }}"
          echo "Registry: ${{ github.event.registry_package.registry }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Package URL: ${{ github.event.registry_package.html_url }}"

  sign-image:
    needs: show-package-details
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: write

    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: "v2.1.1"

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign the published container image
        env:
          COSIGN_EXPERIMENTAL: 1
          COSIGN_YES: "true"
        run: |
          cosign sign \
            --tlog-upload=true \
            ghcr.io/${{ github.repository }}@${{ github.event.registry_package.package_version.container_metadata.tag.digest }}
